# -*- coding: utf-8 -*-
"""Yolo7 A2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nI1n2tei6bNSV4utBkexqVBKwViVM_sV

#Vinicius Reis Veras
#202015568
"""

from google.colab import drive
drive.mount("/content/gdrive")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive

!pwd

import os

if not os.path.isdir("ViniciusReis"):
  os.makedirs("ViniciusReis")

# Commented out IPython magic to ensure Python compatibility.
# %cd ViniciusReis

!git clone https://github.com/WongKinYiu/yolov7.git

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov7

!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7x.pt

"""#Rodando o Yolo7 em imagem e vídeos."""

!pwd

!python detect.py --weights yolov7x.pt --conf 0.5 --img-size 640 --source Turtle.jpg

!python detect.py --weights yolov7.pt --conf 0.5 --img-size 640 --source video.mp4

!python detect.py --weights yolov7x.pt --conf 0.5 --img-size 640 --source Turtle.jpg

!bash scripts/get_coco.sh

!python detect.py --weights yolov7.pt --conf 0.5 --img-size 640 --source Turtle.jpg

"""#os resultados estão na pasta detect(TheCodingBug\yolov7\runs\detect\exp8)
Infelizmente não consegui treinar a inteligência com êxito.
"""



from google.colab import drive
drive.mount('/content/drive')